// generated automatically by ros_hybrid_protoc on  Thu Apr  6 19:10:10 2023
// Do not Edit!
// wrapping message: sys_msgs/SysInfoStat

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: msgs/sys_msgs/SysInfoStat.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysInfoStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *SysInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Stat *SysStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *SysInfoStat) Reset() {
	*x = SysInfoStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_sys_msgs_SysInfoStat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysInfoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfoStat) ProtoMessage() {}

func (x *SysInfoStat) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_sys_msgs_SysInfoStat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfoStat.ProtoReflect.Descriptor instead.
func (*SysInfoStat) Descriptor() ([]byte, []int) {
	return file_msgs_sys_msgs_SysInfoStat_proto_rawDescGZIP(), []int{0}
}

func (x *SysInfoStat) GetInfo() *SysInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SysInfoStat) GetStat() *SysStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

var File_msgs_sys_msgs_SysInfoStat_proto protoreflect.FileDescriptor

var file_msgs_sys_msgs_SysInfoStat_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x68, 0x79, 0x62, 0x72, 0x69, 0x64, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x1a, 0x1b, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2f, 0x53, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x53,
	0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0b,
	0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x79, 0x62, 0x72,
	0x69, 0x64, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x04, 0x73, 0x74, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x79, 0x62, 0x72, 0x69, 0x64,
	0x2e, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_sys_msgs_SysInfoStat_proto_rawDescOnce sync.Once
	file_msgs_sys_msgs_SysInfoStat_proto_rawDescData = file_msgs_sys_msgs_SysInfoStat_proto_rawDesc
)

func file_msgs_sys_msgs_SysInfoStat_proto_rawDescGZIP() []byte {
	file_msgs_sys_msgs_SysInfoStat_proto_rawDescOnce.Do(func() {
		file_msgs_sys_msgs_SysInfoStat_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_sys_msgs_SysInfoStat_proto_rawDescData)
	})
	return file_msgs_sys_msgs_SysInfoStat_proto_rawDescData
}

var file_msgs_sys_msgs_SysInfoStat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msgs_sys_msgs_SysInfoStat_proto_goTypes = []interface{}{
	(*SysInfoStat)(nil), // 0: hybrid.sys_msgs.SysInfoStat
	(*SysInfo)(nil),     // 1: hybrid.sys_msgs.SysInfo
	(*SysStat)(nil),     // 2: hybrid.sys_msgs.SysStat
}
var file_msgs_sys_msgs_SysInfoStat_proto_depIdxs = []int32{
	1, // 0: hybrid.sys_msgs.SysInfoStat.info:type_name -> hybrid.sys_msgs.SysInfo
	2, // 1: hybrid.sys_msgs.SysInfoStat.stat:type_name -> hybrid.sys_msgs.SysStat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msgs_sys_msgs_SysInfoStat_proto_init() }
func file_msgs_sys_msgs_SysInfoStat_proto_init() {
	if File_msgs_sys_msgs_SysInfoStat_proto != nil {
		return
	}
	file_msgs_sys_msgs_SysStat_proto_init()
	file_msgs_sys_msgs_SysInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgs_sys_msgs_SysInfoStat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysInfoStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_sys_msgs_SysInfoStat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgs_sys_msgs_SysInfoStat_proto_goTypes,
		DependencyIndexes: file_msgs_sys_msgs_SysInfoStat_proto_depIdxs,
		MessageInfos:      file_msgs_sys_msgs_SysInfoStat_proto_msgTypes,
	}.Build()
	File_msgs_sys_msgs_SysInfoStat_proto = out.File
	file_msgs_sys_msgs_SysInfoStat_proto_rawDesc = nil
	file_msgs_sys_msgs_SysInfoStat_proto_goTypes = nil
	file_msgs_sys_msgs_SysInfoStat_proto_depIdxs = nil
}
