// generated automatically by ros_hybrid_protoc on  Thu Apr  6 19:56:18 2023
// Do not Edit!
// wrapping message: sys_msgs/SysInfo

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: msgs/sys_msgs/SysInfo.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName      string `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	SystemType    string `protobuf:"bytes,2,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"`
	SystemVersion string `protobuf:"bytes,3,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_sys_msgs_SysInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_sys_msgs_SysInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_msgs_sys_msgs_SysInfo_proto_rawDescGZIP(), []int{0}
}

func (x *SysInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SysInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *SysInfo) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

var File_msgs_sys_msgs_SysInfo_proto protoreflect.FileDescriptor

var file_msgs_sys_msgs_SysInfo_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68,
	0x79, 0x62, 0x72, 0x69, 0x64, 0x2e, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x6e,
	0x0a, 0x07, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_sys_msgs_SysInfo_proto_rawDescOnce sync.Once
	file_msgs_sys_msgs_SysInfo_proto_rawDescData = file_msgs_sys_msgs_SysInfo_proto_rawDesc
)

func file_msgs_sys_msgs_SysInfo_proto_rawDescGZIP() []byte {
	file_msgs_sys_msgs_SysInfo_proto_rawDescOnce.Do(func() {
		file_msgs_sys_msgs_SysInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_sys_msgs_SysInfo_proto_rawDescData)
	})
	return file_msgs_sys_msgs_SysInfo_proto_rawDescData
}

var file_msgs_sys_msgs_SysInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msgs_sys_msgs_SysInfo_proto_goTypes = []interface{}{
	(*SysInfo)(nil), // 0: hybrid.sys_msgs.SysInfo
}
var file_msgs_sys_msgs_SysInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgs_sys_msgs_SysInfo_proto_init() }
func file_msgs_sys_msgs_SysInfo_proto_init() {
	if File_msgs_sys_msgs_SysInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgs_sys_msgs_SysInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_sys_msgs_SysInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgs_sys_msgs_SysInfo_proto_goTypes,
		DependencyIndexes: file_msgs_sys_msgs_SysInfo_proto_depIdxs,
		MessageInfos:      file_msgs_sys_msgs_SysInfo_proto_msgTypes,
	}.Build()
	File_msgs_sys_msgs_SysInfo_proto = out.File
	file_msgs_sys_msgs_SysInfo_proto_rawDesc = nil
	file_msgs_sys_msgs_SysInfo_proto_goTypes = nil
	file_msgs_sys_msgs_SysInfo_proto_depIdxs = nil
}
